name: Deploy Laravel to Addfamily Subdomain

on:
  push:
    branches:
      - fahim  # Specify the branch to trigger deployment

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install LFTP
      - name: Install LFTP
        run: sudo apt-get install -y lftp

      # Step 3: FTP Deploy using LFTP with Active Mode and Debugging
      - name: FTP Deploy with LFTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" -e "
            set ftp:passive-mode off;  # Use active mode
            set debug 3;  # Enable detailed logging
            ls /public_html/addfamily/  # Verify connection with a simple list command
            mirror --reverse --verbose \
            --exclude-glob .git* \
            --exclude-glob .github* \
            --exclude-glob .env \
            --exclude-glob node_modules* \
            --exclude-glob storage/* \
            --exclude-glob vendor/* \
            --exclude-glob bootstrap/cache/* \
            ./ /public_html/addfamily/
            exit
          " "$FTP_SERVER"
