name: Deploy Laravel to Addfamily Subdomain

on:
  push:
    branches:
      - fahim  # Specify the branch to trigger deployment

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: FTP Deploy using SamKirkland's FTP-Deploy-Action
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: "./"
          server-dir: "/public_html/addfamily/"
          log-level: verbose  # Set log level to verbose for detailed output
