name: Deploy Laravel to Addfamily Subdomain

on:
  push:
    branches:
      - fahim  # Adjust to the branch you want to trigger deployment on

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: "./"
          server-dir: "/public_html/addfamily/"
          exclude: |
            .git*
            .github*
            .env
            node_modules
            storage/*.*
            vendor/*.*
          log-level: verbose
          dangerous-clean-slate: true  # This will delete everything in the target directory before uploading


